### ISSUE TITLE
Support the rustdoc theme system

### ISSUE THREAD

**Issue by Cldfire** [Cldfire/ayu-rs#24]
As pointed out in #23, `rustdoc.css` cannot be used by the new theme system in rustdoc. This is because I built the theme to sit on top of the existing rustdoc themes rather than replace them. It would be nice, however, to change this and fully support being integrated into the rustdoc theme system.

The only issue I see with this is that it would result in a greatly increased maintenance burden: any changes to rustdoc's themes would require the same changes to be made to my theme (and rustdoc changes quite a bit).

Anyhow, it's something to consider.

[Relevant rustdoc documentation](https://doc.rust-lang.org/rustdoc/unstable-features.html#a--themes-provide-additional-themes)

**Comment by najamelan** [comment]
I would like to work on this today. I just wonder what is the function of the `rustdoc.css` file? Given that as far as I can tell, stylish and co don't work on `file://` urls. 

I will make another file for now, but if we had a file that can work with rustdoc, it would seem that this would be the most appropriate filename for it...

**Comment by najamelan** [comment]
Actually, I have to take that back. I spent all day on this, but the rustdoc theming is a royal mess. I don't see how I could do anything that makes sense without recompiling rustdoc, and for now I can't make the time for that. Moreover, I started looking into this because I thought it was not possible to inject stuff in a `file://` url from a browser addon like stylish, but actually that's wrong. 

I found the Code Injector for firefox, and just set a rule like ".*target/doc.*" and pasted in the rustdoc.css from this repository and off I go with ayu on "cargo doc --open". In 30 seconds. Making a decent theming system for rustdoc would take weeks...

**Comment by Cldfire** [comment]
Thanks for taking the time to look into this! I agree that it's probably a lot simpler to just override local docs via Stylish. I will open a separate issue to remind me to set that up sometime.

**Comment by evanjs** [comment]
In spite of the comments regarding how this could silently fail when theme specs change in the future, I'm hopeful we'll be able to use ayu with the `--theme` option at some point, especially if it's stabilized [soon](https://github.com/rust-lang/rust/pull/54733).

Though, I'm much more hoping the themes between rustdoc and mdBook can be shared at some point in time...

**Comment by Cldfire** [comment]
A couple weeks ago I took the time to clean everything up and turn this into a polished rustdoc theme. There's currently a PR open to include it officially with rustdoc: https://github.com/rust-lang/rust/pull/71237

Hopefully you'll be a click away from using this theme everywhere soon! For now you can use the file with rustdoc's `--theme` option directly, see https://github.com/Cldfire/rust/blob/rustdoc-ayu-theme/src/librustdoc/html/static/themes/ayu.css

**Comment by evanjs** [comment]
I had been meaning to open a PR re merging the two doc theming systems (mdBook and rustdoc) but the scope is way too large and I don't even know where I'd create that issue.

Thanks for opening this PR!
