### ISSUE TITLE
Upstream colour tweaks

### ISSUE THREAD

**Issue by detly** [Cldfire/ayu-rs#39]
After using this theme on Rust docs, I went looking for the original theme for ST3. However, it's quite different to my eyes — this theme uses slightly darker but (maybe?) more saturated colours. Have you considered upstreaming these changes as a fourth Ayu theme variant? Or releasing it as a new ST3 syntax colour scheme?

**Comment by Cldfire** [comment]
Yeah, the upstream theme has changed quite a bit in the years since I originally put this repo together.

I'm not personally interested in maintaining a ST3 color scheme as I no longer use ST3; and I doubt an upstream of the colors in this repo as a fourth theme variant for the official theme would be accepted (since it's mostly just an old version of Ayu Dark).

If anything, it would be nice to update the themes implemented in this repo to match the new official versions of Ayu Dark; I may look into doing that this year as time allows. Although that will require making a decision about whether or not I should also update the Ayu theme in rustdoc.

**Comment by detly** [comment]
Ah, I just assumed you'd deviated from the original, not that the original had changed. I much prefer the older colours then! Perhaps I'll roll my own theme and drop this then.
